# Generated by Django 5.0.4 on 2025-01-15 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('id_number', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('user_type', models.CharField(choices=[('admin', 'أدمن'), ('employee', 'موظف')], default='employee', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_employee', to='dashboardtravel.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('license_type', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='driver_images/')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_driver', to='dashboardtravel.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='dashboardtravel.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip_date', models.DateField()),
                ('seat_number', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='passenger_images/')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_passenger', to='dashboardtravel.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='dashboardtravel.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seat_count', models.IntegerField()),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='trip_images/')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='dashboardtravel.city')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='dashboardtravel.city')),
                ('travel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.traveltype')),
                ('trip_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.tripcategory')),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='trip_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='dashboardtravel.trip'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.CharField(max_length=100)),
                ('passenger_capacity', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('fuel_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motor_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.driver')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.vehicle'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_number', models.IntegerField()),
                ('trip_date', models.DateField()),
                ('time', models.TimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.passenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.trip')),
                ('type_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.vehicle')),
            ],
        ),
    ]
