# Generated by Django 5.0.4 on 2025-03-16 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TravelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('job_title', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('id_number', models.CharField(max_length=50, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employee_images/')),
                ('user_type', models.CharField(choices=[('admin', 'أدمن'), ('manger', 'مدير'), ('employee', 'موظف'), ('mangertrip', 'مسوول الرحلات'), ('mangerpassenger', 'مسوول المسافرين'), ('manmonay', 'المسوول المالي'), ('customer', 'عميل')], default='customer', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_employee', to='dashboardtravel.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_type', models.CharField(choices=[('tocompany', 'تابع لشركة'), ('tobe', 'تابع لجهه'), ('drivername', 'سواق')], default='drivername', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('license_type', models.CharField(max_length=50, null=True)),
                ('license_number', models.CharField(max_length=50, null=True)),
                ('license_img', models.ImageField(blank=True, null=True, upload_to='driver/license_img/')),
                ('id_number', models.CharField(max_length=50, null=True)),
                ('identify_img', models.ImageField(blank=True, null=True, upload_to='driver/identify_img/')),
                ('passport_number', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='driver/driver_images/')),
                ('date_of_birth', models.DateField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('nationality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities_driver', to='dashboardtravel.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='dashboardtravel.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=50)),
                ('identify_img', models.ImageField(blank=True, null=True, upload_to='passenger/identify_img/')),
                ('passport_number', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_number', models.IntegerField()),
                ('gender', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='passenger/passenger_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities_passenger', to='dashboardtravel.nationality')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_number', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('proof_document', models.CharField(blank=True, max_length=200, null=True)),
                ('proof_document_img', models.ImageField(blank=True, null=True, upload_to='payment/proof_document_img/')),
                ('verified', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_requests', to='dashboardtravel.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('seat_count', models.IntegerField()),
                ('seat_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trip_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=True)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='dashboardtravel.city')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='dashboardtravel.city')),
                ('travel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.traveltype')),
                ('trip_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.tripcategory')),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='trip_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='dashboardtravel.trip'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.trip'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50, null=True)),
                ('plate_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('owner', models.CharField(max_length=100, null=True)),
                ('passenger_capacity', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('fuel_capacity', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('motor_type', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle/vehicle_images/')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='vehicle/')),
                ('date_add', models.DateField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.driver')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardtravel.vehicle'),
        ),
    ]
